version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}
      - run:
          name: "run test"
          command: |
            . venv/bin/activate
            make test
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
      - tests
